
[workspace]
resolver = '2'
members = [
	'libs/rust/services',
	'apps/zerg/api',
]

[workspace.dependencies]

[workspace.lints.rust]
unsafe_code = 'forbid'

[profile.release]
opt-level = 'z'
codegen-units = 1
strip = true
lto = true
