_cloud_regions = {
    "gcp": {
        "ireland": "europe-west1"
        "london": "europe-west2"
        "frankfurt": "europe-west3"
        "paris": "europe-west9"
        "stockholm": "europe-north1"
        "zurich": "europe-west6"
        "tel-aviv": "me-west1"
    }
    "aws": {
        "ireland": "eu-west-1"
        "london": "eu-west-2"
        "frankfurt": "eu-central-1"
        "paris": "eu-west-3"
        "stockholm": "eu-north-1"
        "zurich": "eu-central-2"
        "tel-aviv": "il-central-1"
    }
    "azure": {
        "ireland": "west-europe"
        "london": "uk-south"
        "frankfurt": "germany-west-central"
        "paris": "france-central"
        "stockholm": "sweden-central"
        "zurich": "switzerland-north"
        "tel-aviv": "israel-central"
    }
}
