[package]
name = "zerg_api"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.8"
tokio = { version = "1.45", features = ["full"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
