apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerg-api
  labels:
    app: zerg-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerg-api
  template:
    metadata:
      name: zerg-api
      labels:
        app: zerg-api
    spec:
      containers:
        - name: zerg-api
#          image: yurikrupnik/zerg-api:sha-f1223bb
#          image: yurikrupnik/zerg-api:sha-caec71c
          image: yurikrupnik/zerg-api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGO_URI
              value: "mongodb://localhost:27017"
            - name: PORT
              value: "8080"
      restartPolicy: Always

