apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zerg-api
  labels:
    app: zerg-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: zerg-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s