name: Tag Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
      - '*'   # Triggers on any tag

permissions:
  actions: read
  contents: read

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Setup Bun for JavaScript/TypeScript and Nx
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Setup Python with uv (needed for LangGraph builds)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Setup Rust toolchain (needed for Rust builds)
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Cache Rust dependencies
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
          cache-on-failure: true

      # Install JavaScript/Node dependencies
      - run: bun install --no-cache

      # Install Python dependencies
      - name: Install Python dependencies
        run: uv sync --all-extras --dev

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extract tag name for container tagging
      - run: bun nx affected -t container --parallel=3
        env:
          DOCKER_BUILDKIT: 1
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
