name: Tag Release

on:
  push:
    tags:
      - '*.*.*'  # Triggers on semantic version tags like 1.0.0, 2.1.3, etc.
      - 'v*'     # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  actions: read
  contents: read

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This is the key - sets up proper SHAs for nx
      - name: Derive appropriate SHAs for base and head for `nx run-many` commands
        uses: nrwl/nx-set-shas@v4

      # Setup Bun for JavaScript/TypeScript and Nx
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Setup Python with uv (needed for LangGraph builds)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Setup Rust toolchain (needed for Rust builds)
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Cache Rust dependencies
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
          cache-on-failure: true

      # Install JavaScript/Node dependencies
      - run: bun install --no-cache

      # Install Python dependencies
      - name: Install Python dependencies
        run: uv sync --all-extras --dev

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Container build
        run: bun nx affected --target=container --parallel --max-parallel=3 --configuration=tag
        env:
          DOCKER_BUILDKIT: 1
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
